// Action types
const actionTypes = {

    UPDATE_NAME_INPUT: "UPDATE_NAME_INPUT",
    SUBMIT_INPUT_FORM: "SUBMIT_INPUT_FORM    ",
    SUBMIT_INPUT_FORM_OK: "SUBMIT_INPUT_FORM_OK",
    SUBMIT_INPUT_FORM_ERROR: "SUBMIT_INPUT_FORM_ERROR",
}
export default actionTypes;
